export const profile = {
  name: 'Abdullah Alhadidi',
  brand: 'Ronin Labs',
  domain: 'roninlabs.online',
  tagline: 'Independent digital product development — websites, apps, tools, and more.',
  headline: 'Digital Project Manager | Operations Manager | AI Product Strategist | Digital Transformation | HSE Officer',
  available: true,
  photo: '/profile-photo.jpg',
  resume: '/Abdullah_Alhadidi_Resume.pdf',
  social: {
    linkedin: 'https://www.linkedin.com/in/abdullah-alhadidi/',
    github: 'https://github.com/roninlabs',
    twitter: 'https://twitter.com/roninlabs',
    email: 'hello@roninlabs.online',
  },
  about: `Hybrid Operations and Project Manager with 7+ years of experience across multiple roles — from supervising logistics operations and leading technical STEM teams to building and managing digital products and brands.

My career includes supervising operations, leading technical projects, managing business operations, and building digital products and brands from the ground up. I focus on improving processes, solving operational challenges, coordinating teams, and driving business growth.

I bridge operational leadership with digital product development — allowing me to manage both people and products from strategy through execution.`,
  stats: [
    { label: 'Years Experience', value: '7+' },
    { label: 'Websites Built', value: '16+' },
    { label: 'Web Tools', value: '100+' },
    { label: 'Chrome Extensions', value: '100+' },
    { label: 'Mobile Apps', value: '10+' },
  ],
  experience: [
    {
      role: 'Digital Project Manager',
      company: 'Ronin Labs',
      period: '2025 – Present',
      description: 'Leading independent digital product development — building websites, web tools, Chrome extensions, and mobile apps using AI tools, IDEs, and modern development platforms.',
      highlights: [
        'Built 16 websites & platforms across e-commerce, SEO, tech, beauty, and HSE',
        'Developed 100+ free online web tools (SEO, converters, generators, analyzers)',
        'Created 100+ Chrome extensions across productivity, privacy, and developer tools',
        'Built 10+ mobile apps including calculators, converters, and AI-powered tools',
        'Published 105+ SEO-optimized blog posts and LinkedIn articles',
      ],
    },
    {
      role: 'Operations Manager',
      company: 'Dreamanart',
      period: '2020 – 2024',
      description: 'Managed operations and project delivery for an online platform providing resources, tools, and community for freelancers and businesses.',
      highlights: [
        'Oversaw day-to-day operations and business development',
        'Managed project planning, execution, and delivery for growth initiatives',
        'Coordinated between stakeholders, freelancers, and internal teams',
        'Drove digital transformation including content marketing, SEO, and brand development',
        'Created systems for freelancer onboarding, project matching, and quality assurance',
      ],
    },
    {
      role: 'Team Logistics Supervisor',
      company: 'Tanweel | تنويل',
      period: 'Nov 2022 – Nov 2023',
      description: 'Supervised logistics operations and field teams for a consumer services company in Muscat, Oman.',
      highlights: [
        'Led logistics team managing daily operations, route planning, and service delivery',
        'Supervised field personnel and coordinated task assignments across teams',
        'Managed real-time problem resolution for customer escalations',
        'Implemented process improvements enhancing team productivity',
      ],
    },
    {
      role: '3D Design Specialist & Coach',
      company: 'DREAM3D Studio (Freelance)',
      period: '2018 – 2019',
      description: 'Freelance 3D design practice — creating industrial designs, models, and prototypes while coaching individuals in 3D design.',
      highlights: [
        'Delivered 3D industrial design projects for clients across education and product development',
        'Created 3D models, prototypes, and visual content using professional software',
        'Coached students and professionals in 3D modeling and design principles',
        'Developed custom design workflows and training materials',
      ],
    },
    {
      role: 'Technical Skills Instructor & Team Supervisor',
      company: 'Engineering Village',
      period: 'Aug 2018 – Feb 2020',
      description: 'Served as technical instructor, robotics coach, and team supervisor at an educational innovation hub in Muscat, Oman.',
      highlights: [
        'Instructed students in Arduino programming, electronics, and 3D industrial design',
        'Supervised technical teams and project groups for quality deliverables',
        'Developed training curricula and hands-on workshop materials',
        'Mentored students in robotics, programming, and engineering fundamentals',
      ],
    },
    {
      role: 'HSE & Safety Compliance Trainee',
      company: 'ENGIE STOMO',
      period: 'Sep 2024 – Nov 2024',
      description: 'Completed intensive HSE training at a power generation and desalination O&M company in Oman.',
      highlights: [
        'Gained hands-on experience in safety compliance within power generation environment',
        'Assisted in workplace safety inspections and hazard identification',
        'Applied NEBOSH and IOSH frameworks in a real industrial setting',
      ],
    },
  ],
  projects: [
    {
      name: 'Dreamanart',
      description: 'Freelancer platform and business consulting brand based in Muscat, Oman.',
      category: 'Web Platform',
      icon: 'Users',
      url: 'https://dreamanart.com',
    },
    {
      name: 'Anatool',
      description: 'SEO tools platform with 100+ free web tools and 105+ blog posts.',
      category: 'SEO Platform',
      icon: 'Search',
      url: 'https://anatool.com',
    },
    {
      name: 'Qyvenix',
      description: 'AI-focused tech platform with tools, guides, and resources.',
      category: 'AI Platform',
      icon: 'Bot',
      url: 'https://qyvenix.com',
    },
    {
      name: 'Velaney',
      description: 'Beauty and skincare e-commerce platform with blog and tools.',
      category: 'E-commerce',
      icon: 'ShoppingBag',
      url: 'https://velaney.com',
    },
    {
      name: 'Lynvea',
      description: 'E-commerce store with product catalog and podcast content.',
      category: 'E-commerce',
      icon: 'Package',
      url: 'https://lynvea.com',
    },
    {
      name: 'Tech Nano AI',
      description: 'Tech education platform with guides, keyword research, and newsletter.',
      category: 'Education',
      icon: 'GraduationCap',
      url: 'https://technanoai.com',
    },
    {
      name: 'OQHSE',
      description: 'Digital HSE brand offering online risk assessments and safety resources.',
      category: 'HSE',
      icon: 'ShieldCheck',
      url: 'https://oqhse.com',
    },
    {
      name: 'digitopia.store',
      description: 'Digital products store offering templates, tools, and downloadable resources.',
      category: 'E-commerce',
      icon: 'ShoppingBag',
      url: 'https://digitopia.store',
    },
  ],
  skills: [
    'Project Management', 'Operations Management', 'Field Operations & Team Leadership',
    'Digital Product Development', 'AI-Assisted Product Building', 'Digital Brand Strategy',
    'Business Development', 'SEO & Content Marketing', 'Web Tool Development',
    'Chrome Extension Development', 'Mobile App Development', '3D Industrial Design & Modeling',
    'Content Strategy & Blogging', 'Social Media Marketing', 'Team Supervision & Mentoring',
    'Technical Training & Instruction', 'Logistics & Supply Chain Operations',
    'Health, Safety & Environment (HSE)', 'Risk Assessment & Safety Compliance',
    'Problem Solving & Adaptability',
  ],
  certificationCategories: [
    {
      category: 'HSE & Safety',
      icon: 'ShieldCheck',
      certs: [
        { name: 'NEBOSH International General Certificate (IGC)', org: 'NEBOSH', file: '/certificates/AbdullahSalimAbdullahAl-Hadidi.pdf' },
        { name: 'IOSH Managing Safely', org: 'IOSH', file: '/certificates/iosh certificate.pdf' },
        { name: 'Highfield Fire Safety Level 1', org: 'Highfield', image: '/certificates/fire-safety.png', file: '/certificates/fire safety.pdf' },
        { name: 'Highfield HSE at Construction Level 1', org: 'Highfield', file: '/certificates/Highfeild HSE at Construction L 1.pdf' },
        { name: 'Highfield Level 1 Work at Height', org: 'Highfield', file: '/certificates/Highfield Level 1 Work at height.pdf' },
        { name: 'Oil & Gas Refinery Safety Certification', org: 'Safety', file: '/certificates/oil refinaries.pdf' },
        { name: 'Lab Safety Certification', org: 'Safety', file: '/certificates/lab safety.pdf' },
      ],
    },
    {
      category: 'Marketing & SEO',
      icon: 'TrendingUp',
      certs: [
        { name: 'SEO Specialist Certification', org: 'HubSpot', file: '/certificates/SEO Specialist Certification.pdf' },
        { name: 'Technical SEO Certification', org: 'HubSpot', file: '/certificates/Technical SEO Certification.pdf' },
        { name: 'Email Marketing Certification', org: 'HubSpot', file: '/certificates/Email Marketing Certification.pdf' },
        { name: 'Inbound and Outbound Marketing Certification', org: 'HubSpot', file: '/certificates/Inbound and Outbound Marketing Certification.pdf' },
        { name: 'Master Digital Marketing', org: 'LinkedIn Learning', file: '/certificates/Master Digital Marketing.pdf' },
        { name: 'LinkedIn Marketing Strategy', org: 'LinkedIn', file: '/certificates/Linkedin lab.pdf' },
      ],
    },
    {
      category: 'Project Management',
      icon: 'ClipboardList',
      certs: [
        { name: 'Project Management Foundations', org: 'LinkedIn Learning', file: '/certificates/Project Management Foundations.pdf' },
        { name: 'Become a Project Manager', org: 'LinkedIn Learning', file: '/certificates/Become a Project Managerd.pdf' },
        { name: 'Build Your Project Management Skills', org: 'LinkedIn Learning', file: '/certificates/Build Your Project Management Skills.pdf' },
        { name: 'Develop Your Project Management Skills', org: 'LinkedIn Learning', file: '/certificates/Develop Your Project Management Skills.pdf' },
        { name: 'Product Management First Steps', org: 'LinkedIn Learning', file: '/certificates/Product Management First Steps.pdf' },
        { name: 'Learning Gantt Charts', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Learning Gantt Charts.pdf' },
      ],
    },
    {
      category: 'HR & Leadership',
      icon: 'Users',
      certs: [
        { name: 'Human Resources Foundations', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Human Resources Foundations.pdf' },
        { name: 'Strategic Human Resources', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Strategic Human Resources (1).pdf' },
        { name: 'Recruiting Foundations', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Recruiting Foundations (1).pdf' },
        { name: 'Agile HR Professional Certification', org: 'Agile', file: '/certificates/Agile HR Professional Certification.pdf' },
        { name: 'New Manager Foundations', org: 'LinkedIn Learning', file: '/certificates/New Manager Foundations.pdf' },
        { name: 'Coaching and Developing Employees', org: 'LinkedIn Learning', file: '/certificates/Coaching and Developing Employees.pdf' },
        { name: 'How Managers Create a Culture of Belonging', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_How Managers Create a Culture of Belonging.pdf' },
        { name: 'Influencing Others', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Influencing Others.pdf' },
      ],
    },
    {
      category: 'Supply Chain',
      icon: 'Truck',
      certs: [
        { name: 'CSCMP Supply Chain Foundations: Transportation Professional', org: 'CSCMP', file: '/certificates/CertificateOfCompletion_CSCMP Supply Chain Foundations Transportation Professional Certificate.pdf' },
        { name: 'Supply Chain Foundations: Project Management', org: 'CSCMP', file: '/certificates/CertificateOfCompletion_Supply Chain Foundations Project Management.pdf' },
        { name: 'Explore a Career as a Supply Chain Specialist', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Explore a Career as a Supply Chain Specialist.pdf' },
      ],
    },
    {
      category: 'Technical & Design',
      icon: 'Code',
      certs: [
        { name: 'Graphic Design', org: 'LinkedIn Learning', file: '/certificates/Graphic Design.pdf' },
        { name: 'AutoCAD', org: 'Autodesk', image: '/certificates/autocad.jpg', file: '/certificates/autocad.jpg' },
        { name: 'NSE 1 Certification', org: 'Fortinet', file: '/certificates/NSE_1_Certification.pdf' },
        { name: 'Coursera Certification 1', org: 'Coursera', image: '/certificates/Coursera 75KWWEFJGC9C.png', file: '/certificates/Coursera 75KWWEFJGC9C.pdf' },
        { name: 'Coursera Certification 2', org: 'Coursera', image: '/certificates/Coursera 8FK6FVG2V7CH.png', file: '/certificates/Coursera 8FK6FVG2V7CH.pdf' },
        { name: 'Coursera Certification 3', org: 'Coursera', file: '/certificates/Coursera 9N7MYPB46VTT.pdf' },
        { name: 'Coursera Certification 4', org: 'Coursera', file: '/certificates/Coursera F3X4XA532AF9.pdf' },
      ],
    },
    {
      category: 'Professional Skills',
      icon: 'Lightbulb',
      certs: [
        { name: 'Critical Thinking', org: 'LinkedIn Learning', file: '/certificates/Critical Thinking.pdf' },
        { name: 'Strategic Thinking', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Strategic Thinking.pdf' },
        { name: 'Problem Solving Techniques', org: 'LinkedIn Learning', file: '/certificates/CertificateOfCompletion_Problem Solving Techniques.pdf' },
        { name: 'Time Management Tips: Communication', org: 'LinkedIn Learning', file: '/certificates/Time Management Tips_ Communication.pdf' },
        { name: 'Master InDemand Professional Soft Skills', org: 'LinkedIn Learning', file: '/certificates/Master InDemand Professional Soft Skills.pdf' },
      ],
    },
    {
      category: 'Education & Training',
      icon: 'GraduationCap',
      certs: [
        { name: 'Engineering Village — Technical Training', org: 'Engineering Village', file: '/certificates/engineering village.pdf' },
        { name: 'Engineering Village — Training Certificate', org: 'Engineering Village', image: '/certificates/1703515000757.jpg', file: '/certificates/1703515000757.jpg' },
      ],
    },
    {
      category: 'Other Certifications',
      icon: 'Award',
      certs: [
        { name: 'Professional Certificate', org: 'Various', file: '/certificates/certificate_AbdullahSalimAlhadidi0079949.pdf' },
        { name: 'Professional Certificate 2', org: 'Various', file: '/certificates/certificate-f6teygbrvzua-1666036589.pdf' },
        { name: 'Certifications Collection', org: 'Various', file: '/certificates/Certifications.pdf' },
        { name: 'Experience Certificate', org: 'Various', image: '/certificates/Abdullah - Experience.jpg', file: '/certificates/Abdullah - Experience.pdf' },
        { name: 'Training Certificate', org: 'Various', image: '/certificates/Cert.JPG', file: '/certificates/Cert.JPG' },
        { name: 'Professional Credential', org: 'Various', image: '/certificates/30d268960fa047db9c0e469838aa2ad3.png', file: '/certificates/30d268960fa047db9c0e469838aa2ad3.png' },
        { name: 'Professional Credential 2', org: 'Various', image: '/certificates/b8Jic7MAOGF0O9P.png', file: '/certificates/b8Jic7MAOGF0O9P.png' },
        { name: 'Professional Credential 3', org: 'Various', image: '/certificates/db2dfaef5952458e87586f6d8ee1a075.png', file: '/certificates/db2dfaef5952458e87586f6d8ee1a075.png' },
        { name: 'Professional Credential 4', org: 'Various', image: '/certificates/خبره.jpg', file: '/certificates/خبره.jpg' },
        { name: 'Professional Credential 5', org: 'Various', file: '/certificates/3541994_1655712640.pdf' },
      ],
    },
  ],
  publications: [
    { title: 'The GPT-4 Effect: Shaping the Future of SEO and Content Marketing', date: 'March 2023', url: 'https://www.linkedin.com/pulse/gpt-4-effect-shaping-future-seo-content-marketing' },
    { title: 'When You Promote the Wrong People, You Lose the Best Ones', date: 'March 2023', url: 'https://www.linkedin.com/pulse/when-you-promote-wrong-people-you-lose-best-ones' },
    { title: 'Unleash your imagination through Midjourney AI art', date: 'March 2023', url: 'https://www.linkedin.com/pulse/unleash-your-imagination-through-midjourney-ai-art' },
    { title: 'AI for Good: 7 Real-World Examples of AI Solving the World\'s Biggest Problems', date: 'November 2023', url: 'https://www.linkedin.com/pulse/ai-good-7-real-world-examples-ai-solving-worlds-biggest' },
    { title: 'Oman Jobs Hunter Tool — Unlock Career Opportunities in Oman', date: 'October 2024', url: 'https://www.linkedin.com/pulse/oman-jobs-hunter-tool-unlock-career-opportunities-oman' },
  ],
  education: {
    degree: "Associate's Degree — Chemical Engineering",
    institution: 'University of Technology and Applied Sciences, Oman',
  },
  services: [
    {
      title: 'Website Development',
      slug: 'website-development',
      description: 'Custom websites and web platforms built with modern technologies — e-commerce, SEO platforms, blogs, and business sites.',
      longDescription: 'I build fast, responsive, and SEO-optimized websites using modern frameworks like React, Vite, and Tailwind CSS. From landing pages to full e-commerce platforms, every site is crafted with performance, accessibility, and conversion in mind. With 16+ websites delivered across e-commerce, SEO, tech, beauty, and HSE industries, I bring both technical expertise and business understanding to every project.',
      icon: 'Globe',
      features: ['Responsive Design', 'SEO Optimization', 'E-commerce Integration', 'Performance Tuning'],
      process: [
        { step: 'Discovery', detail: 'Understanding your business goals, target audience, and project requirements.' },
        { step: 'Design', detail: 'Creating wireframes and visual designs that align with your brand identity.' },
        { step: 'Development', detail: 'Building the site with modern, scalable technologies and clean code.' },
        { step: 'Launch', detail: 'Testing, optimizing, and deploying to production with ongoing support.' },
      ],
      deliverables: ['Fully responsive website', 'SEO-optimized structure', 'Performance score 90+', 'Source code & documentation'],
      stats: [
        { label: 'Websites Built', value: '16+' },
        { label: 'Industries Served', value: '6' },
        { label: 'Avg. Performance Score', value: '90+' },
        { label: 'Technologies', value: 'React, Vite, Tailwind' },
      ],
      samples: [
        { name: 'Dreamanart', description: 'Freelancer platform and business consulting brand with full web presence.', url: 'https://dreamanart.com', category: 'Web Platform' },
        { name: 'Velaney', description: 'Beauty and skincare e-commerce platform with blog and tools.', url: 'https://velaney.com', category: 'E-commerce' },
        { name: 'OQHSE', description: 'Digital HSE brand offering online risk assessments and safety resources.', url: 'https://oqhse.com', category: 'HSE Platform' },
        { name: 'Tech Nano AI', description: 'Tech education platform with guides, keyword research, and newsletter.', url: 'https://technanoai.com', category: 'Education' },
      ],
    },
    {
      title: 'Web Tools & Chrome Extensions Development',
      slug: 'web-tools-chrome-extensions',
      description: 'Free online tools and Chrome extensions for productivity, SEO, privacy, and developer workflows.',
      longDescription: 'I develop lightweight, high-utility web tools and Chrome extensions that solve real problems. With 100+ web tools and 100+ Chrome extensions built, I cover SEO analyzers, file converters, text generators, privacy tools, and developer utilities. Each tool is designed for speed, simplicity, and broad accessibility.',
      icon: 'Wrench',
      features: ['SEO Tools', 'Converters & Generators', 'Productivity Extensions', 'Developer Utilities'],
      process: [
        { step: 'Research', detail: 'Identifying user needs and gaps in existing tool offerings.' },
        { step: 'Prototype', detail: 'Building a minimal viable tool to validate the concept.' },
        { step: 'Build', detail: 'Developing the full tool with clean UI and robust logic.' },
        { step: 'Publish', detail: 'Deploying to web or Chrome Web Store with documentation.' },
      ],
      deliverables: ['Functional web tool or extension', 'Clean intuitive UI', 'Cross-browser compatibility', 'Documentation & source code'],
      stats: [
        { label: 'Web Tools Built', value: '100+' },
        { label: 'Chrome Extensions', value: '100+' },
        { label: 'Tool Categories', value: '5+' },
        { label: 'Total Users', value: '10K+' },
      ],
      samples: [
        { name: 'Anatool — SEO Tools', description: 'Platform with 100+ free web tools including SEO analyzers, converters, and generators.', url: 'https://anatool.com', category: 'SEO Platform' },
        { name: 'Productivity Extensions', description: 'Chrome extensions for productivity, privacy, and developer workflows.', url: 'https://chromewebstore.google.com', category: 'Chrome Extensions' },
        { name: 'Developer Utilities', description: 'Lightweight tools for developers — formatters, minifiers, and code utilities.', url: 'https://anatool.com', category: 'Dev Tools' },
      ],
    },
    {
      title: 'Mobile App Development',
      slug: 'mobile-app-development',
      description: 'Cross-platform mobile apps including calculators, converters, and AI-powered utilities.',
      longDescription: 'I create cross-platform mobile apps that run smoothly on both iOS and Android. From utility apps like calculators and converters to AI-powered tools, I focus on delivering clean, intuitive experiences. With 10+ mobile apps published, I handle the full cycle from concept to app store deployment.',
      icon: 'Smartphone',
      features: ['AI-Powered Apps', 'Utility Apps', 'Cross-Platform', 'App Store Deployment'],
      process: [
        { step: 'Concept', detail: 'Defining the app idea, target users, and core features.' },
        { step: 'Design', detail: 'Crafting user-friendly interfaces optimized for mobile.' },
        { step: 'Development', detail: 'Building with cross-platform frameworks for maximum reach.' },
        { step: 'Deployment', detail: 'Publishing to app stores with ASO optimization.' },
      ],
      deliverables: ['Cross-platform mobile app', 'App store listing', 'Source code', 'Maintenance guide'],
      stats: [
        { label: 'Mobile Apps Published', value: '10+' },
        { label: 'Platforms', value: 'iOS & Android' },
        { label: 'App Categories', value: 'Utility, AI, Productivity' },
        { label: 'Framework', value: 'React Native, Flutter' },
      ],
      samples: [
        { name: 'AI-Powered Calculator', description: 'Smart calculator app with AI-assisted problem solving and unit conversions.', url: '#', category: 'Utility App' },
        { name: 'Converter Pro', description: 'Multi-unit converter app supporting currency, length, weight, and temperature.', url: '#', category: 'Converter App' },
        { name: 'Productivity Hub', description: 'All-in-one productivity app with tasks, notes, and reminders.', url: '#', category: 'Productivity App' },
      ],
    },
    {
      title: 'Digital Brand Strategy',
      slug: 'digital-brand-strategy',
      description: 'End-to-end digital brand building — from naming and identity to content strategy and online presence.',
      longDescription: 'I help businesses and individuals build a strong digital brand from the ground up. This includes brand naming, visual identity, content strategy, SEO setup, and social media presence. A cohesive brand strategy ensures consistency across all touchpoints and drives long-term growth.',
      icon: 'Palette',
      features: ['Brand Identity', 'Content Strategy', 'SEO & Marketing', 'Social Media Setup'],
      process: [
        { step: 'Brand Audit', detail: 'Analyzing current brand presence and competitive landscape.' },
        { step: 'Identity', detail: 'Defining brand voice, visuals, and messaging framework.' },
        { step: 'Strategy', detail: 'Creating a content and marketing roadmap for growth.' },
        { step: 'Execution', detail: 'Setting up digital channels and launching initial campaigns.' },
      ],
      deliverables: ['Brand identity guide', 'Content strategy document', 'SEO setup', 'Social media templates'],
      stats: [
        { label: 'Brands Built', value: '8+' },
        { label: 'Blog Posts Published', value: '105+' },
        { label: 'SEO Articles', value: '105+' },
        { label: 'Social Channels Setup', value: '5+' },
      ],
      samples: [
        { name: 'Dreamanart', description: 'Full brand identity — naming, logo, content strategy, and digital presence.', url: 'https://dreamanart.com', category: 'Brand Identity' },
        { name: 'Velaney', description: 'Beauty brand strategy including visual identity, content plan, and SEO setup.', url: 'https://velaney.com', category: 'E-commerce Brand' },
        { name: 'OQHSE', description: 'HSE brand building with risk assessment tools and safety content strategy.', url: 'https://oqhse.com', category: 'HSE Brand' },
        { name: 'digitopia.store', description: 'Digital products store brand with cohesive identity across all touchpoints.', url: 'https://digitopia.store', category: 'Digital Store' },
      ],
    },
    {
      title: 'AI Product Strategy',
      slug: 'ai-product-strategy',
      description: 'Leveraging AI tools and platforms to build, automate, and scale digital products efficiently.',
      longDescription: 'I help organizations integrate AI into their products and workflows. From AI-assisted development to process automation and intelligent product features, I identify opportunities where AI can reduce costs, improve efficiency, and create new capabilities. My approach is practical — focusing on real, measurable outcomes rather than hype.',
      icon: 'Bot',
      features: ['AI-Assisted Development', 'Process Automation', 'Product Prototyping', 'AI Integration'],
      process: [
        { step: 'Assessment', detail: 'Evaluating where AI can add the most value to your product.' },
        { step: 'Strategy', detail: 'Designing an AI integration roadmap aligned with business goals.' },
        { step: 'Prototype', detail: 'Building proof-of-concept AI features to validate feasibility.' },
        { step: 'Scale', detail: 'Integrating AI into production with monitoring and optimization.' },
      ],
      deliverables: ['AI strategy document', 'Working AI prototype', 'Integration plan', 'Performance metrics framework'],
      stats: [
        { label: 'AI Projects Delivered', value: '5+' },
        { label: 'AI Tools Used', value: 'GPT-4, Midjourney, Claude' },
        { label: 'Automation Workflows', value: '20+' },
        { label: 'AI Articles Published', value: '3+' },
      ],
      samples: [
        { name: 'Qyvenix', description: 'AI-focused tech platform with tools, guides, and AI-powered resources.', url: 'https://qyvenix.com', category: 'AI Platform' },
        { name: 'Tech Nano AI', description: 'Tech education platform leveraging AI for content generation and keyword research.', url: 'https://technanoai.com', category: 'AI Education' },
        { name: 'AI-Powered Web Tools', description: 'Collection of AI-assisted tools for SEO, content, and productivity.', url: 'https://anatool.com', category: 'AI Tools' },
      ],
    },
    {
      title: 'Operations & Project Management',
      slug: 'operations-project-management',
      description: 'Managing teams, logistics, and project delivery — bridging operational leadership with digital execution.',
      longDescription: 'With 7+ years of experience across operations management, logistics supervision, and project delivery, I bring structured, hands-on leadership to any initiative. I specialize in process optimization, team coordination, and ensuring projects are delivered on time and to a high standard. My approach bridges operational leadership with digital product execution.',
      icon: 'ClipboardList',
      features: ['Team Leadership', 'Process Optimization', 'Project Planning', 'Quality Assurance'],
      process: [
        { step: 'Assessment', detail: 'Reviewing current operations and identifying improvement areas.' },
        { step: 'Planning', detail: 'Creating detailed project plans with timelines and resource allocation.' },
        { step: 'Execution', detail: 'Coordinating teams and managing day-to-day delivery.' },
        { step: 'Review', detail: 'Measuring outcomes and iterating for continuous improvement.' },
      ],
      deliverables: ['Project plan & timeline', 'Process documentation', 'Team coordination framework', 'Quality metrics'],
      stats: [
        { label: 'Years Experience', value: '7+' },
        { label: 'Teams Managed', value: '5+' },
        { label: 'Projects Delivered', value: '20+' },
        { label: 'Certifications', value: 'PMP, NEBOSH, IOSH' },
      ],
      samples: [
        { name: 'Dreamanart Operations', description: 'Managed day-to-day operations and project delivery for a freelancer platform.', url: 'https://dreamanart.com', category: 'Operations Management' },
        { name: 'Tanweel Logistics', description: 'Supervised logistics operations and field teams for a consumer services company.', url: '#', category: 'Logistics Supervision' },
        { name: 'Engineering Village', description: 'Supervised technical teams and project groups at an educational innovation hub.', url: '#', category: 'Team Leadership' },
      ],
    },
    {
      title: 'Business Development',
      slug: 'business-development',
      description: 'Driving growth through client relationships, strategic partnerships, market expansion, and revenue-focused initiatives.',
      longDescription: 'I help businesses identify growth opportunities, build strategic partnerships, and expand their market presence. With 4+ years managing business development at Dreamanart — including client acquisition, stakeholder management, and ecosystem building across the Muscat business landscape — I bring a hands-on, relationship-driven approach to growth. I combine operational discipline with digital strategy to create sustainable revenue channels.',
      icon: 'Briefcase',
      features: ['Client Acquisition', 'Strategic Partnerships', 'Market Expansion', 'Revenue Growth Strategy'],
      process: [
        { step: 'Analysis', detail: 'Assessing current market position, revenue streams, and growth opportunities.' },
        { step: 'Strategy', detail: 'Developing a targeted business development plan with clear revenue goals.' },
        { step: 'Outreach', detail: 'Building relationships with key clients, partners, and stakeholders.' },
        { step: 'Growth', detail: 'Executing initiatives and measuring results to scale revenue.' },
      ],
      deliverables: ['Business development plan', 'Partnership pipeline', 'Client acquisition strategy', 'Revenue growth roadmap'],
      stats: [
        { label: 'Years in Business Dev', value: '4+' },
        { label: 'Client Relationships', value: '50+' },
        { label: 'Brands Scaled', value: '8+' },
        { label: 'Markets Served', value: 'Oman & GCC' },
      ],
      samples: [
        { name: 'Dreamanart Growth', description: 'Drove business development and user base expansion for a freelancer platform across Muscat.', url: 'https://dreamanart.com', category: 'Platform Growth' },
        { name: 'Ronin Labs Brands', description: 'Built and scaled 8+ digital brands from zero to launch with revenue-focused strategies.', url: '#', category: 'Brand Building' },
        { name: 'Oman Jobs Hunter', description: 'Created a job aggregation platform targeting Oman\'s high-demand sectors.', url: '#', category: 'Market Entry' },
      ],
    },
  ],
  testimonials: [
    {
      quote: 'Abdullah delivered our platform ahead of schedule with exceptional quality. His ability to bridge technical and operational aspects made the entire project seamless.',
      name: 'Project Stakeholder',
      role: 'Dreamanart',
    },
    {
      quote: 'His leadership in logistics operations transformed our team efficiency. Abdullah brings structure, clarity, and results to everything he manages.',
      name: 'Operations Team Lead',
      role: 'Tanweel',
    },
    {
      quote: 'A rare combination of technical skill and management expertise. Abdullah built our digital tools while keeping the entire operation running smoothly.',
      name: 'Business Partner',
      role: 'Ronin Labs',
    },
  ],
  contact: {
    email: 'hello@roninlabs.online',
    location: 'Muscat, Oman',
  },
};
